import { DataSource } from 'typeorm';
import { BasePrice } from './entities/base-price.entity';
import { Coefficient } from './entities/coefficient.entity';

export async function seed(dataSource: DataSource) {
  const baseRepo = dataSource.getRepository(BasePrice);
  const coeffRepo = dataSource.getRepository(Coefficient);

  const basePrices: Array<Partial<BasePrice>> = [
    { projectType: 'webapp', scale: 'small', baseUsd: 2500 },
    { projectType: 'webapp', scale: 'medium', baseUsd: 5000 },
    { projectType: 'webapp', scale: 'large', baseUsd: 9000 },
    { projectType: 'shop', scale: 'small', baseUsd: 3000 },
    { projectType: 'shop', scale: 'medium', baseUsd: 6000 },
    { projectType: 'shop', scale: 'large', baseUsd: 11000 },
    { projectType: 'erp', scale: 'small', baseUsd: 8000 },
    { projectType: 'erp', scale: 'medium', baseUsd: 16000 },
    { projectType: 'erp', scale: 'large', baseUsd: 30000 },
    // additional common types
    { projectType: 'landing', scale: 'small', baseUsd: 800 },
    { projectType: 'landing', scale: 'medium', baseUsd: 1200 },
    { projectType: 'landing', scale: 'large', baseUsd: 2000 },
    { projectType: 'cms', scale: 'small', baseUsd: 1800 },
    { projectType: 'cms', scale: 'medium', baseUsd: 3500 },
    { projectType: 'cms', scale: 'large', baseUsd: 6000 },
    { projectType: 'crm', scale: 'small', baseUsd: 3000 },
    { projectType: 'crm', scale: 'medium', baseUsd: 7000 },
    { projectType: 'crm', scale: 'large', baseUsd: 13000 },
    { projectType: 'mobile', scale: 'small', baseUsd: 3500 },
    { projectType: 'mobile', scale: 'medium', baseUsd: 8000 },
    { projectType: 'mobile', scale: 'large', baseUsd: 15000 },
    { projectType: 'saas', scale: 'small', baseUsd: 6000 },
    { projectType: 'saas', scale: 'medium', baseUsd: 12000 },
    { projectType: 'saas', scale: 'large', baseUsd: 22000 },
  ];

  for (const b of basePrices) {
    const exists = await baseRepo.findOne({ where: { projectType: b.projectType!, scale: b.scale! } });
    if (!exists) await baseRepo.save(baseRepo.create(b));
  }

  const coeffs: Array<Partial<Coefficient>> = [
    // delivery
    { group: 'delivery', key: 'normal', label: 'عادی', value: 1 },
    { group: 'delivery', key: 'fast', label: 'سریع', value: 1.15 },
    { group: 'delivery', key: 'urgent', label: 'فوری', value: 1.35 },
    // complexity
    { group: 'complexity', key: '1', label: 'کم', value: 0.95 },
    { group: 'complexity', key: '2', label: 'متوسط', value: 1 },
    { group: 'complexity', key: '3', label: 'زیاد', value: 1.25 },
    // risk
    { group: 'risk', key: '1', label: 'کم', value: 0.97 },
    { group: 'risk', key: '2', label: 'متوسط', value: 1 },
    { group: 'risk', key: '3', label: 'زیاد', value: 1.2 },
    // technology multipliers
    { group: 'technology', key: 'react', label: 'React', value: 1.05 },
    { group: 'technology', key: 'nextjs', label: 'Next.js', value: 1.08 },
    { group: 'technology', key: 'nestjs', label: 'NestJS', value: 1.04 },
    { group: 'technology', key: 'node', label: 'Node.js', value: 1.02 },
    { group: 'technology', key: 'angular', label: 'Angular', value: 1.07 },
    { group: 'technology', key: 'vue', label: 'Vue', value: 1.05 },
    { group: 'technology', key: 'svelte', label: 'Svelte', value: 1.03 },
    { group: 'technology', key: 'react_native', label: 'React Native', value: 1.06 },
    { group: 'technology', key: 'flutter', label: 'Flutter', value: 1.06 },
    { group: 'technology', key: 'python_django', label: 'Django', value: 1.07 },
    { group: 'technology', key: 'python_fastapi', label: 'FastAPI', value: 1.05 },
    { group: 'technology', key: 'go', label: 'Go', value: 1.06 },
    { group: 'technology', key: 'java_spring', label: 'Spring', value: 1.08 },
    { group: 'technology', key: 'php_laravel', label: 'Laravel', value: 1.04 },
    { group: 'technology', key: 'dotnet', label: '.NET', value: 1.08 },
    { group: 'technology', key: 'postgres', label: 'PostgreSQL', value: 1.03 },
    { group: 'technology', key: 'mysql', label: 'MySQL', value: 1.02 },
    { group: 'technology', key: 'mongodb', label: 'MongoDB', value: 1.03 },
    { group: 'technology', key: 'redis', label: 'Redis', value: 1.02 },
    { group: 'technology', key: 'graphql', label: 'GraphQL', value: 1.05 },
    { group: 'technology', key: 'rest', label: 'REST', value: 1.0 },
    { group: 'technology', key: 'websocket', label: 'WebSocket', value: 1.04 },
    { group: 'technology', key: 'docker', label: 'Docker', value: 1.03 },
    { group: 'technology', key: 'kubernetes', label: 'Kubernetes', value: 1.08 },
    { group: 'technology', key: 'aws', label: 'AWS', value: 1.06 },
    { group: 'technology', key: 'gcp', label: 'GCP', value: 1.06 },
    { group: 'technology', key: 'azure', label: 'Azure', value: 1.06 },
    { group: 'technology', key: 'tailwind', label: 'TailwindCSS', value: 1.01 },
    { group: 'technology', key: 'shadcn', label: 'shadcn/ui', value: 1.01 },
    { group: 'technology', key: 'storybook', label: 'Storybook', value: 1.02 },
    { group: 'technology', key: 'cicd', label: 'CI/CD', value: 1.03 },
    { group: 'technology', key: 'testing', label: 'Test Automation', value: 1.04 },
    // more general-purpose stacks
    { group: 'technology', key: 'nuxt', label: 'Nuxt', value: 1.05 },
    { group: 'technology', key: 'solid', label: 'SolidJS', value: 1.03 },
    { group: 'technology', key: 'astro', label: 'Astro', value: 1.02 },
    { group: 'technology', key: 'remix', label: 'Remix', value: 1.03 },
    { group: 'technology', key: 'expo', label: 'Expo', value: 1.03 },
    { group: 'technology', key: 'electron', label: 'Electron', value: 1.04 },
    { group: 'technology', key: 'capacitor', label: 'Capacitor', value: 1.03 },
    { group: 'technology', key: 'cordova', label: 'Cordova', value: 1.02 },
    { group: 'technology', key: 'rxjs', label: 'RxJS', value: 1.03 },
    { group: 'technology', key: 'zustand', label: 'Zustand', value: 1.01 },
    { group: 'technology', key: 'redux', label: 'Redux', value: 1.03 },
    { group: 'technology', key: 'mobx', label: 'MobX', value: 1.02 },
    { group: 'technology', key: 'prisma', label: 'Prisma', value: 1.03 },
    { group: 'technology', key: 'typeorm', label: 'TypeORM', value: 1.02 },
    { group: 'technology', key: 'sequelize', label: 'Sequelize', value: 1.02 },
    { group: 'technology', key: 'elasticsearch', label: 'Elasticsearch', value: 1.08 },
    { group: 'technology', key: 'meilisearch', label: 'Meilisearch', value: 1.05 },
    { group: 'technology', key: 'kafka', label: 'Apache Kafka', value: 1.08 },
    { group: 'technology', key: 'rabbitmq', label: 'RabbitMQ', value: 1.06 },
    { group: 'technology', key: 'nats', label: 'NATS', value: 1.05 },
    { group: 'technology', key: 'grpc', label: 'gRPC', value: 1.06 },
    { group: 'technology', key: 'otel', label: 'OpenTelemetry', value: 1.04 },
    { group: 'technology', key: 'sentry', label: 'Sentry', value: 1.03 },
    { group: 'technology', key: 'prometheus', label: 'Prometheus', value: 1.04 },
    { group: 'technology', key: 'grafana', label: 'Grafana', value: 1.03 },
    { group: 'technology', key: 'vault', label: 'HashiCorp Vault', value: 1.05 },
    { group: 'technology', key: 'terraform', label: 'Terraform', value: 1.05 },
    { group: 'technology', key: 'ansible', label: 'Ansible', value: 1.04 },
    { group: 'technology', key: 'nginx', label: 'NGINX', value: 1.02 },
    { group: 'technology', key: 'apache', label: 'Apache', value: 1.01 },
    { group: 'technology', key: 'caddy', label: 'Caddy', value: 1.01 },
    { group: 'technology', key: 'edge', label: 'Edge Functions', value: 1.04 },
    { group: 'technology', key: 'vercel', label: 'Vercel', value: 1.02 },
    { group: 'technology', key: 'netlify', label: 'Netlify', value: 1.02 },
    { group: 'technology', key: 'cloudflare', label: 'Cloudflare', value: 1.03 },
    { group: 'technology', key: 'supabase', label: 'Supabase', value: 1.03 },
    { group: 'technology', key: 'firebase', label: 'Firebase', value: 1.04 },
    { group: 'technology', key: 'webrtc', label: 'WebRTC', value: 1.07 },
    { group: 'technology', key: 'threejs', label: 'Three.js', value: 1.07 },
    { group: 'technology', key: 'mapbox', label: 'Mapbox', value: 1.05 },
    { group: 'technology', key: 'leaflet', label: 'Leaflet', value: 1.03 },
    { group: 'technology', key: 'vanilla_js', label: 'Vanilla JS', value: 1.0 },
    // CMS ecosystems
    { group: 'technology', key: 'wordpress', label: 'WordPress', value: 1.02 },
    { group: 'technology', key: 'woocommerce', label: 'WooCommerce', value: 1.03 },
    { group: 'technology', key: 'drupal', label: 'Drupal', value: 1.04 },
    { group: 'technology', key: 'joomla', label: 'Joomla', value: 1.03 },
    { group: 'technology', key: 'strapi', label: 'Strapi', value: 1.04 },
    { group: 'technology', key: 'ghost', label: 'Ghost', value: 1.03 },
    { group: 'technology', key: 'directus', label: 'Directus', value: 1.03 },
    { group: 'technology', key: 'keystone', label: 'KeystoneJS', value: 1.03 },
    { group: 'technology', key: 'sanity', label: 'Sanity', value: 1.04 },
    { group: 'technology', key: 'contentful', label: 'Contentful', value: 1.05 },
    { group: 'technology', key: 'wordpress_pagebuilder', label: 'WP Page Builder', value: 1.02 },
    // Commerce platforms
    { group: 'technology', key: 'magento', label: 'Magento', value: 1.06 },
    { group: 'technology', key: 'shopify', label: 'Shopify', value: 1.05 },
    { group: 'technology', key: 'prestashop', label: 'PrestaShop', value: 1.04 },
    { group: 'technology', key: 'opencart', label: 'OpenCart', value: 1.03 },
    // features
    { group: 'feature', key: 'live_chat', label: 'چت زنده', value: 1.1 },
    { group: 'feature', key: 'i18n', label: 'چندزبانه', value: 1.07 },
    { group: 'feature', key: 'ai', label: 'هوش مصنوعی', value: 1.25 },
    { group: 'feature', key: 'auth', label: 'احراز هویت', value: 1.05 },
    { group: 'feature', key: '2fa', label: 'احراز دومرحله‌ای', value: 1.07 },
    { group: 'feature', key: 'sso', label: 'SSO/LDAP', value: 1.1 },
    { group: 'feature', key: 'notifications', label: 'اعلان‌ها (Push/SMS/Email)', value: 1.06 },
    { group: 'feature', key: 'seo', label: 'SEO پیشرفته', value: 1.05 },
    { group: 'feature', key: 'blog', label: 'وبلاگ', value: 1.03 },
    { group: 'feature', key: 'payment', label: 'پرداخت آنلاین', value: 1.08 },
    { group: 'feature', key: 'subscription', label: 'اشتراک/سابسکریپشن', value: 1.1 },
    { group: 'feature', key: 'invoice', label: 'فاکتور/صدور صورتحساب', value: 1.06 },
    { group: 'feature', key: 'reporting', label: 'گزارش‌گیری', value: 1.06 },
    { group: 'feature', key: 'analytics', label: 'آنالیتیکس', value: 1.05 },
    { group: 'feature', key: 'rbac', label: 'نقش‌ها و دسترسی‌ها', value: 1.07 },
    { group: 'feature', key: 'cms', label: 'مدیریت محتوا', value: 1.05 },
    { group: 'feature', key: 'pwa', label: 'PWA', value: 1.06 },
    { group: 'feature', key: 'offline', label: 'آفلاین/کش پیشرفته', value: 1.07 },
    { group: 'feature', key: 'realtime', label: 'Realtime', value: 1.06 },
    { group: 'feature', key: 'map', label: 'نقشه و مکان‌یابی', value: 1.06 },
    { group: 'feature', key: 'sms', label: 'ارسال پیامک', value: 1.03 },
    { group: 'feature', key: 'email', label: 'ارسال ایمیل', value: 1.03 },
    { group: 'feature', key: 'file_upload', label: 'آپلود فایل', value: 1.04 },
    { group: 'feature', key: 'video_stream', label: 'ویدئو/استریم', value: 1.12 },
    { group: 'feature', key: 'search', label: 'جستجو پیشرفته', value: 1.07 },
    { group: 'feature', key: 'recommendation', label: 'توصیه‌گر', value: 1.12 },
    { group: 'feature', key: 'admin_panel', label: 'پنل ادمین', value: 1.06 },
    { group: 'feature', key: 'inventory', label: 'انبارداری', value: 1.06 },
    { group: 'feature', key: 'shipping', label: 'ارسال و لجستیک', value: 1.06 },
    { group: 'feature', key: 'pos', label: 'POS/صندوق', value: 1.08 },
    { group: 'feature', key: 'chatbot', label: 'چت‌بات', value: 1.1 },
    { group: 'feature', key: 'ocr', label: 'OCR', value: 1.1 },
    { group: 'feature', key: 'fraud_detection', label: 'تشخیص تقلب', value: 1.12 },
    { group: 'feature', key: 'ab_test', label: 'A/B تست', value: 1.05 },
    { group: 'feature', key: 'heatmap', label: 'Heatmap/UX', value: 1.05 },
    { group: 'feature', key: 'data_import', label: 'ورود/خروج داده', value: 1.04 },
    { group: 'feature', key: 'backup', label: 'پشتیبان‌گیری', value: 1.04 },
    { group: 'feature', key: 'monitoring', label: 'مانیتورینگ', value: 1.04 },
    { group: 'feature', key: 'multi_tenant', label: 'Multi-tenant', value: 1.1 },
    { group: 'feature', key: 'webhook', label: 'Webhook', value: 1.03 },
    { group: 'feature', key: 'headless', label: 'Headless API', value: 1.05 },
    { group: 'feature', key: 'bff', label: 'BFF Layer', value: 1.05 },
    { group: 'feature', key: 'queue', label: 'صف پردازش', value: 1.06 },
    { group: 'feature', key: 'cache', label: 'کشینگ پیشرفته', value: 1.05 },
    { group: 'feature', key: 'cdn', label: 'CDN', value: 1.03 },
  ];

  for (const c of coeffs) {
    const exists = await coeffRepo.findOne({ where: { group: c.group!, key: c.key! } });
    if (!exists) await coeffRepo.save(coeffRepo.create(c));
  }
}


